language: go
go:
  - "1.10"

matrix:
  include:
    - language: rust
    - language: go
      go: "1.10"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gfortran

script:
  - go generate
  - pwd
  - ls -lah
  - ls -lah sbr-sys/target/release
  - go test -v -x
