dist: trusty
sudo: required

language: go
go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - "1.10"

before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - export PATH=$HOME/.cargo/bin:$PATH
  - cargo --version
  - sudo apt-get -qq update
  - sudo apt-get install -y gfortran

install:
  - go generate
  - export CGO_LDFLAGS="-L$(pwd)/sbr-sys/target/release/"
  - export LD_LIBRARY_PATH="$(pwd)/sbr-sys/target/release/:$LD_LIBRARY_PATH"

script:
  - go test -c
  - ./sbr-go.test -test.v
