language: go
go:
  - "1.10"

matrix:
  include:
    - language: rust

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gfortran

script:
  - export LD_LIBRARY_PATH=$(pwd):$LD_LIBRARY_PATH
  - go generate
  - ls -lah
  - ls -lah sbr-sys/target/release
  - go test
