language: go
go:
  - "1.10"

before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - export PATH=$HOME/.cargo/bin:$PATH
  - cargo --version
  - sudo apt-get -qq update
  - sudo apt-get install -y gfortran

script:
  - go generate
  - pwd
  - ls -lah
  - ls -lah sbr-sys/target/release
  - go test -c
  - ls -lah
  - ./sbr-go.test -test.v
